# Generated by Django 4.1 on 2022-09-04 07:46

import db.models.base_model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CA', 'cash'), ('DC', 'debit_card'), ('CC', 'credit_card')], max_length=2)),
            ],
            options={
                'db_table': 'bill',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'branch',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=15)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'drug',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_date', models.DateTimeField(blank=True, null=True)),
                ('received_data', models.DateTimeField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.branch')),
            ],
            options={
                'db_table': 'order',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.branch')),
            ],
            options={
                'db_table': 'prescription',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'supplier',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
            options={
                'db_table': 'user',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.branch')),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.drug')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.supplier')),
            ],
            options={
                'db_table': 'product',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('drug', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.prescription')),
            ],
            options={
                'db_table': 'prescription_detail',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.product')),
            ],
            options={
                'db_table': 'order_detail',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.supplier'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('address', models.TextField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.branch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
            options={
                'db_table': 'employee',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='DrugLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration', models.DateTimeField()),
                ('details', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.order')),
            ],
            options={
                'db_table': 'drug_lot',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.druglot'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
            options={
                'db_table': 'doctor',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=14)),
                ('role', models.CharField(choices=[('AD', 'admin'), ('MA', 'manager'), ('ST', 'staff'), ('GE', 'general')], max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
            options={
                'db_table': 'client',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.CreateModel(
            name='BillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.bill')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.employee')),
            ],
            options={
                'db_table': 'bill_detail',
            },
            bases=(models.Model, db.models.base_model.BaseModelMixin),
        ),
        migrations.AddField(
            model_name='bill',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.branch'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.employee'),
        ),
    ]
