version: "3.9"
services:
  pharmacy:
    container_name: pharmacy-container
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql
  
  mysql:
    container_name: mysql-container
    image: mysql:oracle
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pharmacy
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080